[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "Anurag_Project_Testing_New.definitions"
code_location_name = "Anurag_Project_Testing_New"

